### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by ztyaokaixin** [zshicode/Attention-CLX-stock-prediction#16]
为什么在代码中并未发现这个（ARIMA_residuals1.csv')部分

**Comment by ztyaokaixin** [comment]
`ata1 = pd.read_csv("./601988.SH.csv")
data1.index = pd.to_datetime(data1['trade_date'], format='%Y%m%d')
#data1 = data1.drop(['ts_code', 'trade_date', 'turnover_rate', 'volume_ratio', 'pb', 'total_share', 'float_share', 'free_share'], axis=1)
data1 = data1.loc[:, ['open', 'high', 'low', 'close', 'vol', 'amount']]
data_yuan = data1
residuals = pd.read_csv('./ARIMA_residuals1.csv')
residuals.index = pd.to_datetime(residuals['trade_date'])
residuals.pop('trade_date')
data1 = pd.merge(data1, residuals, on='trade_date')
data = data1.iloc[1:3500, :] 
data2 = data1.iloc[3500:, :] 
运行之后报错FileNotFoundError: [Errno 2] No such file or directory: './ARIMA_residuals1.csv'`

**Comment by zshicode** [comment]
首先，运行ARIMA.py进行ARIMA模型预处理步骤。然后，运行神经网络或XGBoost模型。详见[README.md](https://github.com/zshicode/Attention-CLX-stock-prediction#usage)

**Comment by ztyaokaixin** [comment]
运行了arima文件在运行xgboost文件还是报错说那个csv文件不存在



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月27日(周二) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zshicode/Attention-CLX-stock-prediction] 提问 (Issue #16)




 
首先，运行ARIMA.py进行ARIMA模型预处理步骤。然后，运行神经网络或XGBoost模型。详见README.md

**Comment by ztyaokaixin** [comment]
我先运行了arima.py
在运行lstm.py还是报错说csv文件不存在



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月27日(周二) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zshicode/Attention-CLX-stock-prediction] 提问 (Issue #16)




 
首先，运行ARIMA.py进行ARIMA模型预处理步骤。然后，运行神经网络或XGBoost模型。详见README.md

**Comment by ztyaokaixin** [comment]
`WARNING:tensorflow:Please fix your imports. Module tensorflow.python.training.tracking.base has been moved to tensorflow.python.trackable.base. The old module will be deleted in version 2.11.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\code\下载\Attention-CLX-stock-prediction-main\LSTM.py", line 38, in <module>
    data = pd.read_csv('./ARIMA_residuals1.csv')
  File "D:\anaconda\anaconda\envs\zt\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "D:\anaconda\anaconda\envs\zt\lib\site-packages\pandas\util\_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "D:\anaconda\anaconda\envs\zt\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "D:\anaconda\anaconda\envs\zt\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "D:\anaconda\anaconda\envs\zt\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "D:\anaconda\anaconda\envs\zt\lib\site-packages\pandas\io\parsers\readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "D:\anaconda\anaconda\envs\zt\lib\site-packages\pandas\io\common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './ARIMA_residuals1.csv'`
